<?php

use Illuminate\Database\Seeder;

class VwfactoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('vwfactories')->delete();

        \DB::table('vwfactories')->insert(array (
            0 =>
            array (
                'id' => 1,
                'factno' => '1012501',
                'vendorno' => '10125',
            'factname' => 'Shunru Metal Plastic Products(ShenZhen)Co.,Ltd.',
                'factaddr1' => 'Xiang Jiao Tang Industrial',
                'factaddr2' => 'Xue Xiang Country',
                'factcity' => 'Buji',
                'factdistrict' => 'Shenzhen, Longgang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '852-23760069',
                'factfax' => '852-23760553',
                'factemail' => '852-23760553',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d1>',
            ),
            1 =>
            array (
                'id' => 2,
                'factno' => '1012502',
                'vendorno' => '10125',
                'factname' => 'YICK SHUN International Manufacturing Limited',
                'factaddr1' => 'Second Industrial Zone',
                'factaddr2' => 'Shen Wan Town',
                'factcity' => 'Zhong Shan',
                'factdistrict' => '',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86-760)660-7666',
            'factfax' => '(86-760)660-7778',
                'factemail' => 'ysfactory@yickshun.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d2>',
            ),
            2 =>
            array (
                'id' => 3,
                'factno' => '1012503',
                'vendorno' => '10125',
                'factname' => 'YICK SHUN Electronic Toys Manufactory Limited',
                'factaddr1' => 'Second Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Sheng Wan Town',
                'factdistrict' => 'Zhong Shan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86-760)660-7666',
            'factfax' => '(86-760)660-7778',
                'factemail' => 'ysfactory@yickshun.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d3>',
            ),
            3 =>
            array (
                'id' => 4,
                'factno' => '1012504',
                'vendorno' => '10125',
                'factname' => 'Starkis Toys Factory Shixing Xian',
                'factaddr1' => 'Huang Hua Yuan Industrial Park',
                'factaddr2' => 'ShanTang Tou, Tai Ping Zhen',
                'factcity' => 'Shi Xing, Shao Guan',
                'factdistrict' => '',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d4>',
            ),
            4 =>
            array (
                'id' => 5,
                'factno' => '1020001',
                'vendorno' => '10200',
                'factname' => 'TEAM WORK PRINTING FACTORY',
                'factaddr1' => 'No.8, Shui Bian Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Hengli',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(852) 9042 9233',
                'factfax' => '',
                'factemail' => 'frankie@teamworkindustral.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d5>',
            ),
            5 =>
            array (
                'id' => 6,
                'factno' => '1035001',
                'vendorno' => '10350',
                'factname' => 'DongGuan Elite Toys Co.,Ltd.',
                'factaddr1' => 'ShangTun Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Liaobu',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0086-769 83301738 x40',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d6>',
            ),
            6 =>
            array (
                'id' => 7,
                'factno' => '1035002',
                'vendorno' => '10350',
            'factname' => 'DONG GUAN FENG SHALING EVER GLORY (CHUNG HING)TOYS MANUFACTURING FTY',
                'factaddr1' => 'Shiling, You Gan Pu',
                'factaddr2' => '',
                'factcity' => 'Fenggang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0086-769-87771661/87519331',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d7>',
            ),
            7 =>
            array (
                'id' => 8,
                'factno' => '1035003',
                'vendorno' => '10350',
                'factname' => 'Dongguan Elect Plastic Products Co.,Ltd.',
                'factaddr1' => 'Lung Shui Road, Yaukumpao',
                'factaddr2' => '',
                'factcity' => 'Fenggang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0086-769-87772541',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d8>',
            ),
            8 =>
            array (
                'id' => 9,
                'factno' => '1035004',
                'vendorno' => '10350',
            'factname' => 'Vital (BuJi) Manufactory',
                'factaddr1' => 'Shang Shuijin Village',
                'factaddr2' => '',
                'factcity' => 'Buji',
                'factdistrict' => 'Shenzhen, Longgang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0086-0755-89973001',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007d9>',
            ),
            9 =>
            array (
                'id' => 10,
                'factno' => '1035005',
                'vendorno' => '10350',
                'factname' => 'Kader Industrial Company',
                'factaddr1' => 'Yi Chun Industrial District',
                'factaddr2' => '',
                'factcity' => 'Zhongtang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '00852-27981611',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0007b89a>',
            ),
            10 =>
            array (
                'id' => 11,
                'factno' => '1035006',
                'vendorno' => '10350',
                'factname' => 'LUNG CHEONG TOYS',
                'factaddr1' => 'Qiao Li Industrial District',
                'factaddr2' => 'Chang Huang Road',
                'factcity' => 'DongGuan',
                'factdistrict' => 'Dongguan',
                'factstate' => 'GuangDong',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0007b89b>',
            ),
            11 =>
            array (
                'id' => 12,
                'factno' => '1035008',
                'vendorno' => '10350',
                'factname' => 'Dongguan Wise-kid Plastics Products Mfg. Co. Ltd.',
                'factaddr1' => 'Wu Shek Kong Ind. Area, Jushan ',
                'factaddr2' => 'Dongcheng',
                'factcity' => 'Dongguan City',
                'factdistrict' => '',
                'factstate' => 'Guandong Province',
                'factcountry' => 'China',
                'factpostalcd' => 523120,
                'factphone' => '86-769-22265020',
                'factfax' => '86-769-22265056',
                'factemail' => '',
                'factwebsite' => 0,
                'ssmatimestamp' => '<00000000 0007e771>',
            ),
            12 =>
            array (
                'id' => 13,
                'factno' => '1035009',
                'vendorno' => '10350',
                'factname' => 'Buji Heisei Manufactory',
                'factaddr1' => 'No. 135. LianHua Road, Buji Town',
                'factaddr2' => '',
                'factcity' => 'Shenzhen City',
                'factdistrict' => 'Buji',
                'factstate' => 'GuangDong',
                'factcountry' => 'China',
                'factpostalcd' => NULL,
                'factphone' => '86-755-8418 0544',
                'factfax' => '86-755-8418 0094',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00096643>',
            ),
            13 =>
            array (
                'id' => 14,
                'factno' => '1035010',
                'vendorno' => '10350',
                'factname' => 'Epoch Industrial Co. LTD',
                'factaddr1' => 'LONG SHUI ROAD',
                'factaddr2' => '',
                'factcity' => 'DONG GUAN CITY',
                'factdistrict' => '',
                'factstate' => 'GuangDong',
                'factcountry' => 'China',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => 'cchoiepoch@biznetvigator.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0016fae4>',
            ),
            14 =>
            array (
                'id' => 15,
                'factno' => '1040001',
                'vendorno' => '10400',
                'factname' => 'Quercetti & Co SPA',
                'factaddr1' => 'Corso Vigevano 25',
                'factaddr2' => '',
                'factcity' => 'Torino',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'IT',
                'factpostalcd' => 10152,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007db>',
            ),
            15 =>
            array (
                'id' => 16,
                'factno' => '1255001',
                'vendorno' => '12550',
                'factname' => 'Honeykid Toy Manufactory',
                'factaddr1' => 'Fu Choi Industrial Estate',
                'factaddr2' => '',
                'factcity' => 'Chashan',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007dc>',
            ),
            16 =>
            array (
                'id' => 17,
                'factno' => '1312001',
                'vendorno' => '13120',
                'factname' => 'Kiddieland Industrial Ltd.',
                'factaddr1' => 'Gao Li Industrial Area',
                'factaddr2' => '',
                'factcity' => 'Tangxia',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-8791-3892',
                'factfax' => '',
                'factemail' => 'Carmen Chong carmen@kiddieland.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007dd>',
            ),
            17 =>
            array (
                'id' => 18,
                'factno' => '1340501',
                'vendorno' => '13405',
                'factname' => 'Keenway Industries Ltd',
                'factaddr1' => 'Room 1209-1212 New East Ocean Ctr',
                'factaddr2' => '9 Science Museum Rd',
                'factcity' => 'Tsim Sha Tsui East',
                'factdistrict' => 'Kowloon',
                'factstate' => '',
                'factcountry' => 'HK',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007de>',
            ),
            18 =>
            array (
                'id' => 19,
                'factno' => '1340502',
                'vendorno' => '13405',
                'factname' => 'Dongguan Keenway Metal & Plastic Toys Co., Ltd.',
                'factaddr1' => 'Yinshan Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Qingxi',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-7739230',
                'factfax' => '',
                'factemail' => 'office@we-are-keenway.com.cn',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007df>',
            ),
            19 =>
            array (
                'id' => 20,
                'factno' => '1376001',
                'vendorno' => '13760',
                'factname' => 'T.T. Technoplast Co., Ltd.',
                'factaddr1' => '325-328 Mu 6 Ban Chabang',
                'factaddr2' => 'Ratsima-Chokchai Rd',
                'factcity' => 'Muong',
                'factdistrict' => 'Nakhonratchasima 30000',
                'factstate' => '',
                'factcountry' => 'TH',
                'factpostalcd' => NULL,
            'factphone' => '+ 66 (0) 44 212791 - 4',
            'factfax' => '+ 66 (0) 44 212796',
                'factemail' => 'info@technoplast.co.th',
                'factwebsite' => 0,
                'ssmatimestamp' => '<00000000 000007e0>',
            ),
            20 =>
            array (
                'id' => 21,
                'factno' => '1400001',
                'vendorno' => '14000',
                'factname' => 'KOK Hong Matel Plastic Manufactory',
                'factaddr1' => '2 Niu Jiao Keng Road',
                'factaddr2' => 'Bai Zhou Bai Industrial',
                'factcity' => 'Dong Cheng',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0852 2424 3822',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e1>',
            ),
            21 =>
            array (
                'id' => 22,
                'factno' => '1440001',
                'vendorno' => '14400',
            'factname' => 'Motormax Industries (Heyuan) Ltd.',
                'factaddr1' => 'RBI Technology Park',
                'factaddr2' => 'Hi-Tech Development Zone',
                'factcity' => 'Heyuan City',
                'factdistrict' => '',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '762-3600200',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e2>',
            ),
            22 =>
            array (
                'id' => 23,
                'factno' => '1440002',
                'vendorno' => '14400',
                'factname' => 'Dongguan TungFat Toy Fty. Ltd',
                'factaddr1' => 'Red Box Toy Park',
                'factaddr2' => 'Shangsha',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '769-85544256',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e3>',
            ),
            23 =>
            array (
                'id' => 24,
                'factno' => '1453001',
                'vendorno' => '14530',
                'factname' => 'Dongguan Park Plastics Manufactory Ltd',
                'factaddr1' => 'Zhen Dongxing Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Qishi',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e4>',
            ),
            24 =>
            array (
                'id' => 25,
                'factno' => '1454501',
                'vendorno' => '14545',
            'factname' => 'Kidtoys (Shenzhen) Toys Ltd.',
                'factaddr1' => 'Tong Fu Yu Ind. Zone, Tian Fu Road',
                'factaddr2' => '',
                'factcity' => 'Fuyong',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '755-2731-4288',
                'factfax' => '',
                'factemail' => 'danny@fookkey.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e5>',
            ),
            25 =>
            array (
                'id' => 26,
                'factno' => '1455001',
                'vendorno' => '14550',
                'factname' => 'Franki Toys Factory',
                'factaddr1' => 'Luotian Village',
                'factaddr2' => '5 Gaotiandadao',
                'factcity' => 'Songjiang',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86) 755 2714 8016',
                'factfax' => '',
                'factemail' => 'maryfrankitoys@126.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e6>',
            ),
            26 =>
            array (
                'id' => 27,
                'factno' => '1456701',
                'vendorno' => '14567',
                'factname' => 'Dongguan Cheerful Toy Factory Ltd',
                'factaddr1' => 'Tai Sang Industrial Park',
                'factaddr2' => 'Shangsha No.2 Industrial Zone',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e7>',
            ),
            27 =>
            array (
                'id' => 28,
                'factno' => '1456702',
                'vendorno' => '14567',
                'factname' => 'Dongguan Changan Shatou Junjia Plastic Products Factory',
                'factaddr1' => 'No. 88 Hexing Road',
                'factaddr2' => 'South of Shatou',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e8>',
            ),
            28 =>
            array (
                'id' => 29,
                'factno' => '1458201',
                'vendorno' => '14582',
                'factname' => 'CHEERFUL TOY FACTORY LTD',
                'factaddr1' => 'SHANGSHA AREA',
                'factaddr2' => '',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-5412191',
                'factfax' => '',
                'factemail' => 'yu.wong@re.blueboxtoys.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007e9>',
            ),
            29 =>
            array (
                'id' => 30,
                'factno' => '1459001',
                'vendorno' => '14590',
            'factname' => 'Kidtoys (Shenzhen) Toys Ltd.',
                'factaddr1' => 'Tongfuyu Ind. Zone Tianfu Road',
                'factaddr2' => '',
                'factcity' => 'Fuyong',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(852) 2376 3113',
                'factfax' => '',
                'factemail' => ' jacqueline@kidsmart-toys.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007ea>',
            ),
            30 =>
            array (
                'id' => 31,
                'factno' => '1459701',
                'vendorno' => '14597',
                'factname' => 'ONLI Electrical Appliances Enterprise Co. Ltd.',
                'factaddr1' => 'No. 26, Junye Rd.',
                'factaddr2' => 'Sui Xiang Ronggui Town',
                'factcity' => 'Foshan',
                'factdistrict' => 'Shunde District',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86) 757 2838 5668',
                'factfax' => '',
                'factemail' => 'babyonli@sdonli.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007eb>',
            ),
            31 =>
            array (
                'id' => 32,
                'factno' => '1459702',
                'vendorno' => '14597',
            'factname' => 'Yong Hao Chang Toys (Shenzhen) Co., Ltd.',
                'factaddr1' => 'Tang Xia Yong Songgang',
                'factaddr2' => '',
                'factcity' => 'Shenzhen',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86) 755 2986 6230',
                'factfax' => '',
                'factemail' => 'qc@ovationtoys.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007ec>',
            ),
            32 =>
            array (
                'id' => 33,
                'factno' => '1460101',
                'vendorno' => '14601',
                'factname' => 'Dongguan Maple Toys Co., Ltd',
                'factaddr1' => 'Liang Yi, Lingxia Industrial Area',
                'factaddr2' => '',
                'factcity' => 'Liaobu',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-8330 5912',
                'factfax' => '',
                'factemail' => 'anthonychina@mapletoys.com.cn',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007ed>',
            ),
            33 =>
            array (
                'id' => 34,
                'factno' => '1460301',
                'vendorno' => '14603',
                'factname' => 'Chern Shianq Industry Co., Ltd.',
                'factaddr1' => 'No.115, Sung Kang Sec.',
                'factaddr2' => 'Guang Shen Rd',
                'factcity' => 'Bao An',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-755-27091668',
                'factfax' => '',
                'factemail' => 'sales@foammax-cs.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007ee>',
            ),
            34 =>
            array (
                'id' => 35,
                'factno' => '1460302',
                'vendorno' => '14603',
                'factname' => 'Fun Mart Industry Co., Ltd.',
                'factaddr1' => 'No.7, Shui Chan Rd',
                'factaddr2' => 'Yan Chuan',
                'factcity' => 'Song Kang',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '86-755-2707-0001',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00021b11>',
            ),
            35 =>
            array (
                'id' => 36,
                'factno' => '1460401',
                'vendorno' => '14604',
                'factname' => 'YUEN KWONG PLASTICS MFG., CO., LTD',
                'factaddr1' => 'Yong Da Li Industrial Park, Huang Dong',
                'factaddr2' => '',
                'factcity' => 'Fenggang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => 523660,
                'factphone' => '86-769-87518476',
                'factfax' => '',
                'factemail' => 'Weldon@ykmfg.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007ef>',
            ),
            36 =>
            array (
                'id' => 37,
                'factno' => '1460701',
                'vendorno' => '14607',
                'factname' => 'ARTOY INDUSTRIAL FACTORY',
                'factaddr1' => 'Gong Keng Industrial Park, Group 2',
                'factaddr2' => 'Shi Jing, Fu Min Estate',
                'factcity' => 'Guanlan',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-13622373488',
                'factfax' => '',
                'factemail' => 'Raphael@artoy.com / nero@artoy.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f0>',
            ),
            37 =>
            array (
                'id' => 38,
                'factno' => '1461501',
                'vendorno' => '14615',
                'factname' => 'Tree Toys Corp',
                'factaddr1' => 'No. 5 Industrial W. 2nd Road',
                'factaddr2' => 'Chang Bin Industrial Area',
                'factcity' => 'Lugang',
                'factdistrict' => '',
                'factstate' => 'Chang Hwa County',
                'factcountry' => 'TW',
                'factpostalcd' => NULL,
                'factphone' => '886 4 781 0050',
                'factfax' => '886 4 781 3210',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f1>',
            ),
            38 =>
            array (
                'id' => 39,
                'factno' => '1461502',
                'vendorno' => '14615',
                'factname' => 'Ningbo Tree Toys Co. LTD',
                'factaddr1' => 'No. 28 Moju Road',
                'factaddr2' => 'Wonga Industrial Zone',
                'factcity' => 'Beilune',
                'factdistrict' => 'Ningbo',
                'factstate' => 'Zhejiang',
                'factcountry' => 'China',
                'factpostalcd' => NULL,
                'factphone' => '8657486832859',
                'factfax' => '',
                'factemail' => 'evelync@treetoys.com.tw',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00097db2>',
            ),
            39 =>
            array (
                'id' => 40,
                'factno' => '1461701',
                'vendorno' => '14617',
                'factname' => 'Dongguan Liao Bu Jia Feng Plastic Toy Factory',
                'factaddr1' => 'Tang Chun Ping Ling Industrial Area',
                'factaddr2' => '',
                'factcity' => 'Liaobu Zhen',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-869-8326-9208',
                'factfax' => '',
                'factemail' => 'production@jiafengfty.com
production@jiafengfty.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f2>',
            ),
            40 =>
            array (
                'id' => 41,
                'factno' => '1461702',
                'vendorno' => '14617',
            'factname' => 'Guangdong Huawei Toys Crat (Group) Co., LTD',
                'factaddr1' => 'Yutin Road Chenghau Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Chenghai City',
                'factdistrict' => 'Guangdong',
                'factstate' => '',
                'factcountry' => 'China',
                'factpostalcd' => NULL,
                'factphone' => '75483250900 x888',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00097db1>',
            ),
            41 =>
            array (
                'id' => 42,
                'factno' => '1461901',
                'vendorno' => '14619',
                'factname' => 'Luen Hing Tai Toys Factory',
                'factaddr1' => 'Qichong Road',
                'factaddr2' => '',
                'factcity' => 'Dachong Town',
                'factdistrict' => 'Zhong Shan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => 528476,
                'factphone' => '86-760-87721439',
                'factfax' => '',
                'factemail' => 'prodlht@dragonglobal.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f3>',
            ),
            42 =>
            array (
                'id' => 43,
                'factno' => '1462901',
                'vendorno' => '14629',
            'factname' => 'Dongguan Huanjing Taiway (Shingkee) Toys Factory',
                'factaddr1' => 'Huangjiang Village',
                'factaddr2' => '',
                'factcity' => 'Huangjiang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f4>',
            ),
            43 =>
            array (
                'id' => 44,
                'factno' => '1463301',
                'vendorno' => '14633',
                'factname' => 'Zhejiang Playwell Toy Co.,Ltd',
                'factaddr1' => '117# Jincheng Road',
                'factaddr2' => '',
                'factcity' => 'Xindeng Town',
                'factdistrict' => 'Fuyang',
                'factstate' => 'Zhejiang',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-571-63218661',
                'factfax' => '86-571-63250627',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f5>',
            ),
            44 =>
            array (
                'id' => 45,
                'factno' => '1464101',
                'vendorno' => '14641',
                'factname' => 'Dongguan Richbo Plastic MFY. Co.',
                'factaddr1' => 'Lan-Gi Yuan Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Xiegang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-8776 5500',
                'factfax' => '',
                'factemail' => 'prod@richbo.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f6>',
            ),
            45 =>
            array (
                'id' => 46,
                'factno' => '1464102',
                'vendorno' => '30108',
                'factname' => 'GuoTong Printing Products Ltd',
                'factaddr1' => '16, The Second RD.,',
                'factaddr2' => '3rd Sheung Sha Ind\'l Zone',
                'factcity' => 'Changanzhen',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f2ad5>',
            ),
            46 =>
            array (
                'id' => 47,
                'factno' => '1464901',
                'vendorno' => '14649',
                'factname' => 'Dongguan Chen Ye Toys Manufactory',
                'factaddr1' => 'Da Li Village',
                'factaddr2' => '',
                'factcity' => 'Qingxi',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f7>',
            ),
            47 =>
            array (
                'id' => 48,
                'factno' => '1465101',
                'vendorno' => '14651',
            'factname' => 'MAGIKER (MEI ZHOU) FACTORY',
                'factaddr1' => 'A3 AREA, DONGSHENG INDUSTRIAL AREA',
                'factaddr2' => '',
                'factcity' => 'MEIZHOU CITY',
                'factdistrict' => '',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86 1350 989 3068',
                'factfax' => '',
                'factemail' => 'info@simpsons.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f8>',
            ),
            48 =>
            array (
                'id' => 49,
                'factno' => '1465501',
                'vendorno' => '14655',
                'factname' => 'Dong Guan, Tang Xia, Jian Ye Plastic Factory',
                'factaddr1' => '2, East Four Across Rd,',
                'factaddr2' => '1st Industrial Estate, Lian Hu, Tang Xia',
                'factcity' => 'Gong Guan',
                'factdistrict' => '',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86 769) 8207 5278',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007f9>',
            ),
            49 =>
            array (
                'id' => 50,
                'factno' => '1465601',
                'vendorno' => '14656',
                'factname' => 'HI-TECH PLASTIC & METAL MANUFACTORY',
                'factaddr1' => '9, Gong Ye Lu, Wu Lian Cun',
                'factaddr2' => '',
                'factcity' => 'Fenggang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(852)90106136',
                'factfax' => '',
                'factemail' => 'renee@magicstarz.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007fa>',
            ),
            50 =>
            array (
                'id' => 51,
                'factno' => '1466201',
                'vendorno' => '14662',
                'factname' => 'BaoLingDeng Industry & Trade Co., Ltd.',
                'factaddr1' => 'Donghai Road',
                'factaddr2' => '',
                'factcity' => 'Taizhou',
                'factdistrict' => '',
                'factstate' => 'Zhejiang',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0086-532-80790320',
                'factfax' => '0086-532-80790319',
                'factemail' => 'guocheng11111@163.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007fb>',
            ),
            51 =>
            array (
                'id' => 52,
                'factno' => '1466701',
                'vendorno' => '14667',
                'factname' => 'Germton Enterprises Ltd',
                'factaddr1' => 'He Tian Xia industrial District',
                'factaddr2' => '',
                'factcity' => 'Shi Jei Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769 8663- 3899',
                'factfax' => '',
                'factemail' => 'patrickyuen@germton.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007fc>',
            ),
            52 =>
            array (
                'id' => 53,
                'factno' => '1467001',
                'vendorno' => '14670',
                'factname' => 'Shenzhen Patech Plastic & Electronic Manufactory',
                'factaddr1' => 'Bai Gongao Industrial Estate',
                'factaddr2' => 'Xikeng New Village',
                'factcity' => 'GuangLan Town',
                'factdistrict' => 'Shenzhen, Longang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-755 28013905',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007fd>',
            ),
            53 =>
            array (
                'id' => 54,
                'factno' => '1467501',
                'vendorno' => '14675',
                'factname' => 'DONG GUAN HUANG JIAN LONG JIAN TIAN HONG FA TOYS FACTORY',
                'factaddr1' => 'No.3, Fu Qiang Str. Long Jiean Tiean',
                'factaddr2' => 'Huang Jiang Town',
                'factcity' => 'Huangjiang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '0769-83634187',
                'factfax' => '',
                'factemail' => 'larrisa@3smilingtiger.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000007fe>',
            ),
            54 =>
            array (
                'id' => 55,
                'factno' => '1467701',
                'vendorno' => '14677',
                'factname' => 'Yunhe Hunter Wooden Products Co Ltd',
                'factaddr1' => 'Wooden Toy Indust Park',
                'factaddr2' => '',
                'factcity' => 'Yunhe',
                'factdistrict' => '',
                'factstate' => 'Zhejiang',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '00 86 577511 3510',
                'factfax' => '0086 577 511 3520',
                'factemail' => 'yunh@helotoy.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000222e8>',
            ),
            55 =>
            array (
                'id' => 56,
                'factno' => '1467702',
                'vendorno' => '14677',
                'factname' => 'D& S Metal & Plastic Factory',
                'factaddr1' => 'Guanyayuan Tsuen',
                'factaddr2' => 'Bantian',
                'factcity' => 'Bu Ji',
                'factdistrict' => 'Shenzhen, Longang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '00852 2605391',
                'factfax' => '00 852 2605366',
                'factemail' => 'Felix@dstoys.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000222ee>',
            ),
            56 =>
            array (
                'id' => 57,
                'factno' => '1467801',
                'vendorno' => '14678',
                'factname' => 'All Kids Coloring Co., Limited',
                'factaddr1' => 'Unit 4, 9/F., Fook Yip Bldg.',
                'factaddr2' => '53-57 Kwai Fung Crescent',
                'factcity' => 'Kwai Chung',
                'factdistrict' => '',
                'factstate' => 'New Territory',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-755-2787-4949',
                'factfax' => '86-755-2775-4469',
                'factemail' => 'victor@washabletoys.com',
                'factwebsite' => 0,
                'ssmatimestamp' => '<00000000 000007ff>',
            ),
            57 =>
            array (
                'id' => 58,
                'factno' => '1467901',
                'vendorno' => '14679',
                'factname' => 'Technic Star Products',
                'factaddr1' => 'Zhu Shan Industrial Park',
                'factaddr2' => 'Ma Ti Shan Village, Gang Tou',
                'factcity' => 'Buji',
                'factdistrict' => 'Shenzhen, Longang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86-755) 8471 9228',
            'factfax' => '(86-755) 8471 9256',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000801>',
            ),
            58 =>
            array (
                'id' => 59,
                'factno' => '1468101',
                'vendorno' => '14681',
                'factname' => 'Hoi Ming Plastic Products Factory',
                'factaddr1' => 'No 10, Kai Ming Road',
                'factaddr2' => 'Niushipo, Liu Yue',
                'factcity' => 'Henggang',
                'factdistrict' => 'Shenzhen, Longgang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '852-2858-1198',
                'factfax' => '',
                'factemail' => 'cecilia@handsomegroup.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000802>',
            ),
            59 =>
            array (
                'id' => 60,
                'factno' => '1468501',
                'vendorno' => '14685',
                'factname' => 'Future Art Ware Co., Ltd.',
                'factaddr1' => 'Jiankou Shunwang Street',
                'factaddr2' => '',
                'factcity' => 'Zhucheng City',
                'factdistrict' => '',
                'factstate' => 'Shandong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-536-366-4334',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000803>',
            ),
            60 =>
            array (
                'id' => 61,
                'factno' => '1468701',
                'vendorno' => '14687',
                'factname' => 'Zhejiang Sorbo Electronic Co., Ltd',
                'factaddr1' => 'No 215, Dongfang Road',
                'factaddr2' => 'Ouhai Economic Development Zone',
                'factcity' => 'Wenzhou',
                'factdistrict' => '',
                'factstate' => 'Zhejiang',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0002328c>',
            ),
            61 =>
            array (
                'id' => 62,
                'factno' => '1468702',
                'vendorno' => '14687',
                'factname' => 'Wenzhou Donteng Electronic Co., Ltd',
                'factaddr1' => 'No.88, Sancha Road',
                'factaddr2' => 'Sanyang',
                'factcity' => 'Wenzhou',
                'factdistrict' => '',
                'factstate' => 'Zhejiang',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0002328d>',
            ),
            62 =>
            array (
                'id' => 63,
                'factno' => '1469201',
                'vendorno' => '14692',
                'factname' => 'Superfine Holding LTD',
                'factaddr1' => 'DaDong Road',
                'factaddr2' => 'The 1st Industrial Area of DaZhou',
                'factcity' => 'QiaoTou Town',
                'factdistrict' => 'DongGuan City',
                'factstate' => 'GuangDong Province',
                'factcountry' => 'China',
                'factpostalcd' => 523525,
                'factphone' => '86076981036355',
                'factfax' => '',
                'factemail' => 'Becky Liu',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0006f544>',
            ),
            63 =>
            array (
                'id' => 64,
                'factno' => '1471101',
                'vendorno' => '14711',
                'factname' => 'Dong Guan Wang Yat Plastic Toys Co., Ltd.',
                'factaddr1' => 'Di Tang Ling Industrial Region, ',
                'factaddr2' => 'Da Tang Village',
                'factcity' => 'Da Ling Shan Town',
                'factdistrict' => 'Dongguan City',
                'factstate' => 'Guang Dong',
                'factcountry' => 'China',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000762a5>',
            ),
            64 =>
            array (
                'id' => 65,
                'factno' => '1473201',
                'vendorno' => '14732',
            'factname' => 'Qingdao Dream Arts & Crafts Co., Ltd. (DA)',
                'factaddr1' => 'PuDong Town Jimo',
                'factaddr2' => '',
                'factcity' => 'Qingdao',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '053286657895',
                'factfax' => '053286657876',
                'factemail' => 'dream@163169.net',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f2ad3>',
            ),
            65 =>
            array (
                'id' => 66,
                'factno' => '1473202',
                'vendorno' => '14732',
            'factname' => 'Qingdao Tongshang Toys Co., Ltd. (TS)',
                'factaddr1' => 'South Xifuzhen, Cheng-Qu,',
                'factaddr2' => '',
                'factcity' => 'Qingdao',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '0532-8665-7895',
                'factfax' => '0532-8665-7876',
                'factemail' => 'jongjun@e-toystory.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f2ad6>',
            ),
            66 =>
            array (
                'id' => 67,
                'factno' => '1473203',
                'vendorno' => '14732',
            'factname' => 'ZHUCHENG HUANUO CRAFTWORK CO.,LTD. (ZC)',
                'factaddr1' => 'NORTH SECTION OF BUS STATION’S',
                'factaddr2' => 'BUSINESS BUILDING,ZHANQIAN ',
                'factcity' => 'SHANDONG',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '0536-6090072',
                'factfax' => '0536-6090986',
                'factemail' => 'ojinwoo@zchuanuo.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f2ad7>',
            ),
            67 =>
            array (
                'id' => 68,
                'factno' => '1473204',
                'vendorno' => '14732',
            'factname' => 'QINGDAO SHENGLIN ARTS & CRAFTS CO.,LTD (SN)',
                'factaddr1' => 'FANGJIATUAN VILLAGE,EAST OF SHANGHAI  ',
                'factaddr2' => 'LAIXI',
                'factcity' => 'Qingdao',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '86-532-87426779',
                'factfax' => '86-532-87426875',
                'factemail' => 'qingdaoshenglin@126.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f2ad8>',
            ),
            68 =>
            array (
                'id' => 69,
                'factno' => '1473205',
                'vendorno' => '14732',
            'factname' => 'Inhesion Industrial (M) Sdn. Bhd., Malaysia (INM)',
                'factaddr1' => 'Lot 6083 & 6084, Jalan Haji Abdul Manan,',
                'factaddr2' => 'Mukim Kapar 42200 Klang, Selangor Darul',
                'factcity' => 'Ehsan',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'Malaysia',
                'factpostalcd' => NULL,
            'factphone' => '60(3) 3392 7045',
            'factfax' => '60(3) 3392 7535',
                'factemail' => 'skantha@inhesion.com.my ',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f32a1>',
            ),
            69 =>
            array (
                'id' => 70,
                'factno' => '1473206',
                'vendorno' => '14732',
            'factname' => 'Dongguan Chip Wo Plastic & Metal Prod. Co. Ltd. (CW)',
                'factaddr1' => 'Qiao Li Industrial Area, ',
                'factaddr2' => 'Chang Pang Town',
                'factcity' => 'Dongguan Guangdong',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '86-769-83333994',
                'factfax' => '86-769-83337218',
                'factemail' => 'brian@chupwo.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f32a2>',
            ),
            70 =>
            array (
                'id' => 71,
                'factno' => '1473207',
                'vendorno' => '14732',
            'factname' => 'DONGGUAN QINGXI SANZHONG YONG CHENG HANDBAGS FTY (SL)',
                'factaddr1' => 'SANZHONG QU',
                'factaddr2' => 'QINGXI ZHEN',
                'factcity' => 'Dongguan',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '769-87733074',
                'factfax' => '769-87733074',
                'factemail' => 'ws075@biznetvigator.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f32a3>',
            ),
            71 =>
            array (
                'id' => 72,
                'factno' => '1473208',
                'vendorno' => '14732',
            'factname' => 'Dongguan Fine Makers Gift Factory Company Limited (FM)',
                'factaddr1' => 'Si Jia Industrial Area II',
                'factaddr2' => 'Shi Jie Town',
                'factcity' => 'Dong Guan Guangdong',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '86-769-86632019',
                'factfax' => '86-769-86632058',
                'factemail' => 'anita@fmdgl.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 000f32a4>',
            ),
            72 =>
            array (
                'id' => 73,
                'factno' => '2367501',
                'vendorno' => '23675',
                'factname' => 'Forever True International',
                'factaddr1' => 'Km10,Pham Van Dong Road',
                'factaddr2' => '',
                'factcity' => 'Hai Phong',
                'factdistrict' => 'Kien Thuy',
                'factstate' => '',
                'factcountry' => 'VN',
                'factpostalcd' => NULL,
                'factphone' => '84-982881704',
                'factfax' => '',
                'factemail' => 'sunkin@gftforce.com.cn/ftv.jane@gftforce.com.cn',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000804>',
            ),
            73 =>
            array (
                'id' => 74,
                'factno' => '2367502',
                'vendorno' => '23675',
                'factname' => 'Gakken',
                'factaddr1' => 'New Industrial Development Zone',
                'factaddr2' => 'Xiao Bian',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '852-27394366',
                'factfax' => '',
                'factemail' => 'barry@gakkenhk.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000805>',
            ),
            74 =>
            array (
                'id' => 75,
                'factno' => '2367503',
                'vendorno' => '23675',
                'factname' => 'Longshore Limited',
                'factaddr1' => 'Lan-Gi Yuan Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Xiegang',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-87765500/1',
                'factfax' => '',
                'factemail' => 'bteam@longshore.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000806>',
            ),
            75 =>
            array (
                'id' => 76,
                'factno' => '2367504',
                'vendorno' => '23675',
                'factname' => 'Lung Cheong',
                'factaddr1' => 'ZHOU WU INDUSTRIAL DISTRICT',
                'factaddr2' => '',
                'factcity' => 'Dong Cheng',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-8683 6266-311',
                'factfax' => '',
                'factemail' => 'martyl@lungcheong.com.cn',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000807>',
            ),
            76 =>
            array (
                'id' => 77,
                'factno' => '2367505',
                'vendorno' => '23675',
                'factname' => 'Max Peace',
                'factaddr1' => 'Da Huan Industrial District',
                'factaddr2' => 'Yi Xian Rd',
                'factcity' => 'Zhang Jia Bian',
                'factdistrict' => 'Zhong Shan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-760 - 2369 6023',
                'factfax' => '',
                'factemail' => 'samsonchoy@zctl.net / zhengxuexian@zctl.net',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000808>',
            ),
            77 =>
            array (
                'id' => 78,
                'factno' => '2367506',
                'vendorno' => '23675',
                'factname' => 'Qualidux',
                'factaddr1' => '189 Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Hengguan',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '852-2552-8221 (055)',
                'factfax' => '',
                'factemail' => 'wongcw@qualidux.com.hk',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000809>',
            ),
            78 =>
            array (
                'id' => 79,
                'factno' => '2367507',
                'vendorno' => '23675',
                'factname' => 'Sane Product',
                'factaddr1' => 'B32 Zhen Kou 1st Ind. Est.',
                'factaddr2' => 'Zhenkou',
                'factcity' => 'Humen',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '86-769-85510069',
                'factfax' => '',
                'factemail' => 'nancyw@saneuchoice.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0000080a>',
            ),
            79 =>
            array (
                'id' => 80,
                'factno' => '2367508',
                'vendorno' => '23675',
                'factname' => 'Tomy Thailand',
                'factaddr1' => '60/59 Moo 19, Tambol Klongnuang',
                'factaddr2' => '',
                'factcity' => 'Amphur Klongluang',
                'factdistrict' => '',
                'factstate' => 'Pathumthani',
                'factcountry' => 'TH',
                'factpostalcd' => 12120,
            'factphone' => '(662) 529-0680',
                'factfax' => '',
                'factemail' => 'mak_kokweng@tomy.co.th',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0000080b>',
            ),
            80 =>
            array (
                'id' => 81,
                'factno' => '2367509',
                'vendorno' => '23675',
                'factname' => 'Topco Manufacture Ltd',
                'factaddr1' => 'No. 167 Min Sheng Road',
                'factaddr2' => 'Taiping Industrial Zone',
                'factcity' => 'Lanhe Town',
                'factdistrict' => 'Pan Yu District',
                'factstate' => 'Guangzhou',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(852)2191 3823',
                'factfax' => '',
                'factemail' => 'sylvial@topcohk.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0000080c>',
            ),
            81 =>
            array (
                'id' => 82,
                'factno' => '2367510',
                'vendorno' => '23675',
                'factname' => 'Wah Shing',
                'factaddr1' => 'CHANG LONG SHAN',
                'factaddr2' => 'NAN LING VILLAGE',
                'factcity' => 'Buji',
                'factdistrict' => 'Shenzhen, Longang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '852-28969147',
                'factfax' => '',
                'factemail' => 'RoyChan@wahshing.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0000080d>',
            ),
            82 =>
            array (
                'id' => 83,
                'factno' => '2367511',
                'vendorno' => '23675',
                'factname' => 'Well Hopes',
                'factaddr1' => 'SHATOU SOUTH INDUSTRIAL AREA',
                'factaddr2' => '',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '852-2897-2663',
                'factfax' => '',
                'factemail' => 'michelle@wellhopesplastic.com / alina@wellhopesplastic.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0000080e>',
            ),
            83 =>
            array (
                'id' => 84,
                'factno' => '2367512',
                'vendorno' => '23675',
                'factname' => 'Well Power',
                'factaddr1' => 'A8,BEI WEI INDUSTRIAL ZONE',
                'factaddr2' => '',
                'factcity' => 'GETDD',
                'factdistrict' => '',
                'factstate' => 'GUANGZHOU',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '86-20-8220-9903 (200)',
                'factfax' => '',
                'factemail' => 'liza@talenttop.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 0000080f>',
            ),
            84 =>
            array (
                'id' => 85,
                'factno' => '2664501',
                'vendorno' => '26645',
            'factname' => 'Intex Toys & Plastic Electronic (Dongguan) Ltd.',
                'factaddr1' => 'Weng Tang Industrial District',
                'factaddr2' => '',
                'factcity' => 'Dong Cheng',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
            'factphone' => '(86) 769 2229 5251',
                'factfax' => '',
                'factemail' => 'vicky@intexhk.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000810>',
            ),
            85 =>
            array (
                'id' => 86,
                'factno' => '2732001',
                'vendorno' => '27320',
                'factname' => 'Marilis Ltd',
                'factaddr1' => '4 Amsterdam St.',
                'factaddr2' => '',
                'factcity' => 'Tel Aviv',
                'factdistrict' => '',
                'factstate' => '',
                'factcountry' => 'IS',
                'factpostalcd' => NULL,
                'factphone' => '972-3-5292787',
                'factfax' => '972-3-5292838',
                'factemail' => 'Saray@marilis.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000811>',
            ),
            86 =>
            array (
                'id' => 87,
                'factno' => '2903101',
                'vendorno' => '29031',
                'factname' => 'Dongguan TaiFat Toy Factory Ltd',
                'factaddr1' => 'Red Box Toy Park, Shangha Area',
                'factaddr2' => '',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000812>',
            ),
            87 =>
            array (
                'id' => 88,
                'factno' => '2903102',
                'vendorno' => '29031',
                'factname' => 'Dongguan Tungfat Toy Factory. Co. Ltd',
                'factaddr1' => 'Red Box Toy Park, Shangsha Area',
                'factaddr2' => '',
                'factcity' => 'Chang\'an Town',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000813>',
            ),
            88 =>
            array (
                'id' => 89,
                'factno' => '2903103',
                'vendorno' => '29031',
                'factname' => 'Shiner Metal and Plastic Factory',
                'factaddr1' => 'Zhang Ge',
                'factaddr2' => '',
                'factcity' => 'Guanlan',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000814>',
            ),
            89 =>
            array (
                'id' => 90,
                'factno' => '2903104',
                'vendorno' => '29031',
                'factname' => 'Dong Guan Tang Xia Wide Bright Diecasting & Plastic Toys Factory',
                'factaddr1' => '150 Chun Feng Road',
                'factaddr2' => 'Long Bei Ling Village',
                'factcity' => 'Tang Xia Zhen',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000815>',
            ),
            90 =>
            array (
                'id' => 91,
                'factno' => '2903105',
                'vendorno' => '29031',
                'factname' => 'Dongguan Park Plastics Manufactory Ltd',
                'factaddr1' => 'Zhen Dongxing Industrial Zone',
                'factaddr2' => '',
                'factcity' => 'Qishi',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000816>',
            ),
            91 =>
            array (
                'id' => 92,
                'factno' => '2903106',
                'vendorno' => '29031',
                'factname' => 'Shenzhen Long Gong Qu Bao An Wah Shing Manufactory',
                'factaddr1' => 'Wodu, Baoan Village',
                'factaddr2' => '',
                'factcity' => 'Henggang',
                'factdistrict' => 'Shenzhen, Longgang',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000817>',
            ),
            92 =>
            array (
                'id' => 93,
                'factno' => '2903107',
                'vendorno' => '29031',
                'factname' => 'Heng Gang Bao Ah Wah Shing Mfy',
                'factaddr1' => 'Wah Shing Industrial Centre',
                'factaddr2' => 'Heng Gang Shen',
                'factcity' => 'Long Qu',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '755-2868-6995',
                'factfax' => '',
                'factemail' => 'alice.ng@paws-ltd.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000818>',
            ),
            93 =>
            array (
                'id' => 94,
                'factno' => '2903108',
                'vendorno' => '29031',
                'factname' => 'Guanghua Arts & Crafts Co. Ltd.',
                'factaddr1' => 'No 196 West Zhongshan Rd',
                'factaddr2' => '',
                'factcity' => 'Yunhe',
                'factdistrict' => 'Ningbo',
                'factstate' => 'Zhejiang',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '',
                'factfax' => '',
                'factemail' => '',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00021341>',
            ),
            94 =>
            array (
                'id' => 95,
                'factno' => '2903109',
                'vendorno' => '29031',
                'factname' => 'Dongguan Maple Toys Co., Ltd',
                'factaddr1' => 'Liang Yi, Lingxia Industrial Area',
                'factaddr2' => '',
                'factcity' => 'Liaobu',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
                'factphone' => '86-769-8330 5912',
                'factfax' => '',
                'factemail' => 'anthonychina@mapletoys.com.cn',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00021342>',
            ),
            95 =>
            array (
                'id' => 96,
                'factno' => '2903110',
                'vendorno' => '29031',
                'factname' => 'Franki Toys Factory',
                'factaddr1' => 'Luotian Village',
                'factaddr2' => '5 Gaotiandadao',
                'factcity' => 'Songjiang',
                'factdistrict' => 'Shenzhen, Bao An',
                'factstate' => 'Guangdong',
                'factcountry' => 'CHINA',
                'factpostalcd' => NULL,
            'factphone' => '(86) 755 2714 8016',
                'factfax' => '',
                'factemail' => 'maryfrankitoys@126.com',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00022304>',
            ),
            96 =>
            array (
                'id' => 97,
                'factno' => '2948101',
                'vendorno' => '29481',
                'factname' => 'TETRO',
                'factaddr1' => 'No. 79 Li Jia Fang Industrial District',
                'factaddr2' => '',
                'factcity' => 'Shipai',
                'factdistrict' => 'Dongguan',
                'factstate' => 'Guangdong',
                'factcountry' => 'CN',
                'factpostalcd' => NULL,
                'factphone' => '852-2811-2474',
                'factfax' => '',
                'factemail' => 'lawrence.luo@tetro.com.cn',
                'factwebsite' => NULL,
                'ssmatimestamp' => '<00000000 00000819>',
            ),
        ));


    }
}