<?php

use Illuminate\Database\Seeder;

class VwlabsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file/
     *
     * @return void
     */
    public function run()
    {


        \DB::table('vwlabs')->delete();

        \DB::table('vwlabs')->insert(array (
            0 =>
            array (
                'wdt_ID' => 1,
                'id' => 1,
                'labname' => 'Bureau Veritas Hong Kong Limited - Kowloon Bay Office',
                'labaddr1' => '1/F., Pacific Trade Centre',
                'labaddr2' => '',
                'labcity' => 'Kowloon Bay',
                'labdistrict' => '',
                'labstate' => 'Kowloon',
                'labcountry' => 'Hong Kong',
                'labpostalcode' => '00852',
                'labphone' => '852 2331 0888',
                'labfax' => '852 2331 0889',
                'labemail' => '',
                'labwebsite' => 'www.bureauveritas.com/cps',
            ),
            1 =>
            array (
                'wdt_ID' => 2,
                'id' => 2,
                'labname' => 'Bureau Veritas US',
                'labaddr1' => '100 Northpointe Pkwy',
                'labaddr2' => '',
                'labcity' => 'Buffalo',
                'labdistrict' => '',
                'labstate' => 'NY',
                'labcountry' => 'US',
                'labpostalcode' => '14228-1884',
                'labphone' => '716-505-3300',
                'labfax' => '716-505-3301',
                'labemail' => '',
                'labwebsite' => 'www.eps.bureauveritas.com',
            ),
            2 =>
            array (
                'wdt_ID' => 3,
                'id' => 3,
            'labname' => 'Bureau Veritas Hong Kong Limited (Shenzhen Office)',
                'labaddr1' => '1&4th Flr, B Building, Minlida Ind Bldg',
                'labaddr2' => 'Honghualing Industrial Park, Xili Town',
                'labcity' => 'Shenzhen',
                'labdistrict' => 'Nanshan',
                'labstate' => 'Guangdong',
                'labcountry' => 'Peoples Republic of China',
                'labpostalcode' => '518055',
            'labphone' => '(86) 755 8618 5200',
            'labfax' => '(86) 755 8618 5206',
                'labemail' => '',
                'labwebsite' => 'www.bureauveritas.com/cps',
            ),
            3 =>
            array (
                'wdt_ID' => 4,
                'id' => 4,
            'labname' => 'Intertek Testing Services (Thailand) Limited',
                'labaddr1' => '5/1 Soi Phaholyothin 28, Phaholyothin Rd',
                'labaddr2' => 'Lardyao',
                'labcity' => 'Chatuchak',
                'labdistrict' => '',
                'labstate' => 'Bangkok',
                'labcountry' => 'Thailand',
                'labpostalcode' => '10900',
                'labphone' => '662-9390661',
                'labfax' => '662-9305783',
                'labemail' => '',
                'labwebsite' => 'www.intertek.com',
            ),
            4 =>
            array (
                'wdt_ID' => 5,
                'id' => 5,
                'labname' => 'Intertek Testing Services Hong Kong Limited',
                'labaddr1' => '7/F., Garment Center',
                'labaddr2' => '576 Castle Peak Road',
                'labcity' => 'Hong Kong',
                'labdistrict' => '',
                'labstate' => 'Kowloon',
                'labcountry' => 'Hong Kong',
                'labpostalcode' => '',
                'labphone' => '852 2173 8728',
                'labfax' => '852 2785 8570',
                'labemail' => 'karen.ng@intertek.com',
                'labwebsite' => 'www.intertek.com',
            ),
            5 =>
            array (
                'wdt_ID' => 6,
                'id' => 6,
                'labname' => 'Intertek Testing Services Co. Ltd., Shanghai',
                'labaddr1' => 'Block B, Jinling Business Square',
                'labaddr2' => 'No. 801, Yishan Road',
                'labcity' => 'Shanghai',
                'labdistrict' => '',
                'labstate' => 'Shanghai',
                'labcountry' => 'Peoples Republic of China',
                'labpostalcode' => '200233',
            'labphone' => '(86) 21 61279718',
            'labfax' => '(86) 21 61279740',
                'labemail' => '',
                'labwebsite' => 'www.intertek.com',
            ),
            6 =>
            array (
                'wdt_ID' => 7,
                'id' => 7,
                'labname' => 'Intertek Testing Services Shenzhen Ltd.-TFH Division',
                'labaddr1' => '7/F., Shekou Technology Main Building',
                'labaddr2' => 'Industrial 7th Rd',
                'labcity' => 'Shekou',
                'labdistrict' => 'Shenzhen',
                'labstate' => '',
                'labcountry' => 'CN',
                'labpostalcode' => '518067',
            'labphone' => '(86-755)2602 0111',
            'labfax' => '(86-755) 2683 7118/9',
                'labemail' => '',
                'labwebsite' => '',
            ),
            7 =>
            array (
                'wdt_ID' => 8,
                'id' => 8,
                'labname' => 'Intertek Consumer Goods North America',
                'labaddr1' => '545 East Algonquin Road',
                'labaddr2' => '',
                'labcity' => 'Arlington Heights',
                'labdistrict' => '',
                'labstate' => 'Illinois',
                'labcountry' => 'USA',
                'labpostalcode' => '60005',
                'labphone' => '847-871-1051',
                'labfax' => '847-439-6156',
                'labemail' => '',
                'labwebsite' => 'www.intertek.com',
            ),
            8 =>
            array (
                'wdt_ID' => 9,
                'id' => 9,
                'labname' => 'Istituto Italiano Sicurezza dei Giocattoli S. r. I.',
                'labaddr1' => 'Via Europa 28',
                'labaddr2' => '',
                'labcity' => 'Cabiate',
                'labdistrict' => '',
                'labstate' => 'Como',
                'labcountry' => 'Italy',
                'labpostalcode' => '22060',
            'labphone' => '(0039) 031 768400',
            'labfax' => '(0039) 031 756782',
                'labemail' => 'info@icqglobal.com',
                'labwebsite' => 'www.giocattolisicuri.it',
            ),
            9 =>
            array (
                'wdt_ID' => 10,
                'id' => 10,
                'labname' => 'HK Standards & Testing Centre',
                'labaddr1' => '10 Dai Wang Street',
                'labaddr2' => 'Taipo Industrial Estate',
                'labcity' => 'Tai Po',
                'labdistrict' => '',
                'labstate' => 'New Territories',
                'labcountry' => 'Hong Kong',
                'labpostalcode' => '00000',
                'labphone' => '852-2666 1888',
                'labfax' => '852-2664 4353',
                'labemail' => '',
                'labwebsite' => 'www.hkstc.org',
            ),
            10 =>
            array (
                'wdt_ID' => 11,
                'id' => 11,
            'labname' => 'SGS (Thailand) Limited',
                'labaddr1' => '41/23 Rama 3rd Road Soi 59',
                'labaddr2' => 'Chongnonsee',
                'labcity' => 'Yannawa',
                'labdistrict' => '',
                'labstate' => 'Bangkok',
                'labcountry' => 'Thailand',
                'labpostalcode' => '10120',
                'labphone' => '662-6830541',
                'labfax' => '662-2947484',
                'labemail' => '',
                'labwebsite' => 'www.th.sgs.com',
            ),
            11 =>
            array (
                'wdt_ID' => 12,
                'id' => 12,
                'labname' => 'SGS Hong Kong Limited',
                'labaddr1' => '28/F, Metropole Square, 2 On Yiu Street',
                'labaddr2' => 'Siu Lek Yuen, Shatin',
                'labcity' => 'Hong Kong',
                'labdistrict' => '',
                'labstate' => 'NT',
                'labcountry' => 'Hong Kong',
                'labpostalcode' => '',
                'labphone' => '852-2609 9698',
                'labfax' => '852-2356 7502',
                'labemail' => 'tammy.cheng@sgs.com',
                'labwebsite' => 'www.hk.sgs.com',
            ),
            12 =>
            array (
                'wdt_ID' => 13,
                'id' => 13,
                'labname' => 'SGS CTS-US',
                'labaddr1' => '291 Fairfield Ave',
                'labaddr2' => '',
                'labcity' => 'Fairfield',
                'labdistrict' => '',
                'labstate' => 'NJ',
                'labcountry' => 'USA',
                'labpostalcode' => '07004',
                'labphone' => '973-461-7914',
                'labfax' => '973-575-7175',
                'labemail' => 'russell_nichols@sgs.com',
                'labwebsite' => 'http://www.us.sgs.com/consumer_testing_us',
            ),
            13 =>
            array (
                'wdt_ID' => 14,
                'id' => 14,
            'labname' => 'Specialized Technology Resources(H.K.) Ltd.',
                'labaddr1' => '16/F.-17/F., Tower B, Regent Centre',
                'labaddr2' => '63 Wo Yi Hop Road',
                'labcity' => 'Kwai Chung',
                'labdistrict' => 'N.T.',
                'labstate' => '',
                'labcountry' => 'HK',
                'labpostalcode' => '',
            'labphone' => '(852)2423 3092',
            'labfax' => '(852) 2480 5436',
                'labemail' => '',
                'labwebsite' => '',
            ),
            14 =>
            array (
                'wdt_ID' => 15,
                'id' => 15,
                'labname' => 'Specialized Technology Resources, Inc.',
                'labaddr1' => '10 Water Street',
                'labaddr2' => '',
                'labcity' => 'Enfield',
                'labdistrict' => '',
                'labstate' => 'CT',
                'labcountry' => 'USA',
                'labpostalcode' => '06082',
                'labphone' => '860-749-8371',
                'labfax' => '860-749-8234',
                'labemail' => 'edward.kozloski@strquality.com',
                'labwebsite' => 'www.strlabs.com',
            ),
            15 =>
            array (
                'wdt_ID' => 16,
                'id' => 16,
            'labname' => 'Specialized Technology Resources (Shanghai) Ltd. Shenzhen',
                'labaddr1' => 'No. 29, 6 South Keji Road',
                'labaddr2' => 'High-Tech Industrial Park',
                'labcity' => 'Shenzhen',
                'labdistrict' => 'Nanshan',
                'labstate' => 'Guangdong',
                'labcountry' => 'Peoples Republic of China',
                'labpostalcode' => '518057',
                'labphone' => '0086-0755-26018618',
                'labfax' => '0086-0755-26010554',
                'labemail' => 'samkam@strcn.com',
                'labwebsite' => 'www.strcn.com',
            ),
            16 =>
            array (
                'wdt_ID' => 17,
                'id' => 18,
                'labname' => 'SGS Shenzhen',
                'labaddr1' => '2,4,5/F Oastar Bldg',
                'labaddr2' => 'Zhongkong RD',
                'labcity' => 'Shangmeilin',
                'labdistrict' => 'Shenzhen',
                'labstate' => '',
                'labcountry' => 'CN',
                'labpostalcode' => '',
            'labphone' => '(86-755)83114358',
            'labfax' => '(86-755)83106190',
                'labemail' => 'sgs.china@sgs.com',
                'labwebsite' => 'www.cn.sgs.com',
            ),
            17 =>
            array (
                'wdt_ID' => 18,
                'id' => 21,
                'labname' => 'Factory Tested',
                'labaddr1' => 'X-Ray Test for lead in Substrate',
                'labaddr2' => '',
                'labcity' => '.',
                'labdistrict' => '',
                'labstate' => '.',
                'labcountry' => '',
                'labpostalcode' => '',
                'labphone' => '',
                'labfax' => '',
                'labemail' => '',
                'labwebsite' => '',
            ),
            18 =>
            array (
                'wdt_ID' => 19,
                'id' => 22,
                'labname' => 'International Playthings, LLC',
                'labaddr1' => '75D Lacakawanna Ave',
                'labaddr2' => '',
                'labcity' => 'Parsippany',
                'labdistrict' => '',
                'labstate' => 'NJ',
                'labcountry' => 'US',
                'labpostalcode' => '07054',
                'labphone' => '973-316-2500',
                'labfax' => '973-316-5883',
                'labemail' => 'safety@intplay.com',
                'labwebsite' => 'www.intplay.com',
            ),
            19 =>
            array (
                'wdt_ID' => 20,
                'id' => 23,
                'labname' => 'Intertek Labtest UK Limited',
                'labaddr1' => 'Centre Court',
                'labaddr2' => 'Meridan Business Park',
                'labcity' => 'Leicester',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'UK',
                'labpostalcode' => 'LE19 1WD',
            'labphone' => '44 (0) 116 263 0330',
            'labfax' => '44 (0) 116 263 0311/12',
                'labemail' => '',
                'labwebsite' => 'www.intertek.com/consumergoods',
            ),
            20 =>
            array (
                'wdt_ID' => 21,
                'id' => 24,
                'labname' => 'Intertek Testing Service Taiwan Ltd.',
                'labaddr1' => '8/F., No. 423, Ruiguang Road',
                'labaddr2' => 'Neihu District',
                'labcity' => 'Taipei 114',
                'labdistrict' => '',
                'labstate' => 'Taiwan',
                'labcountry' => 'CN',
                'labpostalcode' => '',
            'labphone' => '(886-2) 6602-2888',
            'labfax' => '(886-2) 6602-2410',
                'labemail' => '',
                'labwebsite' => '',
            ),
            21 =>
            array (
                'wdt_ID' => 22,
                'id' => 25,
                'labname' => 'SGS United Kingdom Ltd.',
                'labaddr1' => 'Consumer Testing Services, Oakwood House',
                'labaddr2' => 'City Road',
                'labcity' => 'Bradford',
                'labdistrict' => '',
                'labstate' => 'West Yorkshire',
                'labcountry' => 'UK',
                'labpostalcode' => 'BD8 8JY',
                'labphone' => '01274-760400',
                'labfax' => '01274-760418',
                'labemail' => '',
                'labwebsite' => '',
            ),
            22 =>
            array (
                'wdt_ID' => 23,
                'id' => 26,
            'labname' => 'ACTS Testing Labs (H.K.) Ltd.',
                'labaddr1' => '1/F Pacific Trade Centre',
                'labaddr2' => '2 Kai Hing Road',
                'labcity' => 'Kowloon Bay',
                'labdistrict' => '',
                'labstate' => 'Kowloon',
                'labcountry' => 'HK',
                'labpostalcode' => '',
            'labphone' => '(852) 2331 0888',
            'labfax' => '(852) 2331 0889',
                'labemail' => '',
                'labwebsite' => '',
            ),
            23 =>
            array (
                'wdt_ID' => 24,
                'id' => 27,
                'labname' => 'SGS Taiwan Limited',
                'labaddr1' => 'No. 136-1, Wu Kung Road',
                'labaddr2' => 'WuKu Industrial Zone',
                'labcity' => 'Taipei',
                'labdistrict' => '',
                'labstate' => 'Taiwan',
                'labcountry' => 'CN',
                'labpostalcode' => '',
            'labphone' => '(886-2) 2299-3939',
            'labfax' => '(886-2) 2299-3237',
                'labemail' => '',
                'labwebsite' => 'www.sgs.com.tw',
            ),
            24 =>
            array (
                'wdt_ID' => 25,
                'id' => 28,
                'labname' => 'TUV Rheinland Hong Kong Ltd.',
                'labaddr1' => '9-10/F., Oriental News Building',
                'labaddr2' => '7 Wang Tei Road',
                'labcity' => 'Kowloon Bay',
                'labdistrict' => '',
                'labstate' => 'Kowloon',
                'labcountry' => 'HK',
                'labpostalcode' => '',
            'labphone' => '(852) 2192 1000',
            'labfax' => '(852) 2192 1003',
                'labemail' => 'info@hk.chn.tuv.com',
                'labwebsite' => 'www.chn.tuv.com',
            ),
            25 =>
            array (
                'wdt_ID' => 26,
                'id' => 29,
                'labname' => 'Intertek Testing Services Guangzhou Ltd.',
                'labaddr1' => 'E401, E501, E601, E701, E801',
                'labaddr2' => 'No 7-2, Caipin Road',
                'labcity' => 'Guangzhou Science City',
                'labdistrict' => 'GETDO',
                'labstate' => 'Guangzhou',
                'labcountry' => 'CN',
                'labpostalcode' => '510663',
            'labphone' => '(86-20) 3210 2100',
            'labfax' => '(86-20) 3220 6061',
                'labemail' => '',
                'labwebsite' => 'www.intertek-labtest.com.cn',
            ),
            26 =>
            array (
                'wdt_ID' => 27,
                'id' => 30,
                'labname' => 'Toys Testing Lab of Guangdong Inspection and Quarantine Tech',
                'labaddr1' => '11/F., B Tower',
                'labaddr2' => '66 Huacheng Avenue',
                'labcity' => 'Guangzhou',
                'labdistrict' => '',
                'labstate' => 'Guangdong',
                'labcountry' => 'CN',
                'labpostalcode' => '',
                'labphone' => '86-20-3829 0660',
                'labfax' => '86-20-3829 0599',
                'labemail' => 'mdg@iqtc.cn',
                'labwebsite' => 'www.iqtc.cn',
            ),
            27 =>
            array (
                'wdt_ID' => 28,
                'id' => 31,
                'labname' => 'SGS Multilab CTS',
                'labaddr1' => '20-22 rue C. Paradinas',
                'labaddr2' => '',
                'labcity' => 'Clichy',
                'labdistrict' => '',
                'labstate' => 'Cedex',
                'labcountry' => 'FR',
                'labpostalcode' => '92583',
            'labphone' => '33 (0) 1.41.06.95.71',
            'labfax' => '33 (0) 1.41.06.95.78',
                'labemail' => 'www.sgsgroupe.fr',
                'labwebsite' => '',
            ),
            28 =>
            array (
                'wdt_ID' => 29,
                'id' => 57,
                'labname' => 'Bureau Veritas France',
                'labaddr1' => 'Rue John Hadley--BP 20431',
                'labaddr2' => '59658 Villeneuve d\'Ascq cedex France',
                'labcity' => '',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'France',
                'labpostalcode' => '',
                'labphone' => '330320463456',
                'labfax' => '330320469906',
                'labemail' => '',
                'labwebsite' => 'www.cps.bureauveritas.com',
            ),
            29 =>
            array (
                'wdt_ID' => 30,
                'id' => 58,
                'labname' => 'Taiwan Powco XRF Technology',
                'labaddr1' => '15th Fl, No 129',
                'labaddr2' => 'Fu Hsin Raod, Sec 1',
                'labcity' => 'Taipei',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'Taiwan, R.O.C.',
                'labpostalcode' => '',
                'labphone' => '0227312167',
                'labfax' => '0227732302',
                'labemail' => 'taipow@ms5.hinet.net',
                'labwebsite' => '',
            ),
            30 =>
            array (
                'wdt_ID' => 31,
                'id' => 59,
                'labname' => 'IP XRF Technology',
                'labaddr1' => '75 D Lackawanna Ave',
                'labaddr2' => '',
                'labcity' => 'Parsippany',
                'labdistrict' => '',
                'labstate' => 'NJ',
                'labcountry' => 'USA',
                'labpostalcode' => '07054',
                'labphone' => '1-800-631-1272',
                'labfax' => '',
                'labemail' => '',
                'labwebsite' => 'www.intplay.com',
            ),
            31 =>
            array (
                'wdt_ID' => 32,
                'id' => 60,
                'labname' => 'Skylab/Playgo XRF Technology',
                'labaddr1' => 'Playgo Toys Manufacturing Ltd.',
                'labaddr2' => '',
                'labcity' => '',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => '',
                'labpostalcode' => '',
                'labphone' => '86-769-86963888',
                'labfax' => '86-769-86961653',
                'labemail' => 'info@playgochina.cn',
                'labwebsite' => '',
            ),
            32 =>
            array (
                'wdt_ID' => 33,
                'id' => 61,
                'labname' => 'CMA Testing and Certification Laboratories',
                'labaddr1' => 'Room 1302 Yan Hing Centre',
                'labaddr2' => '9-13 Wong Chuk Yeung St',
                'labcity' => 'Fo Tan ',
                'labdistrict' => 'Shatin',
                'labstate' => 'NT',
                'labcountry' => 'Hong Kong',
                'labpostalcode' => '',
                'labphone' => '852-26988198',
                'labfax' => '852-26954177',
                'labemail' => 'info@cmatcl.com',
                'labwebsite' => 'www.cmatcl.com',
            ),
            33 =>
            array (
                'wdt_ID' => 34,
                'id' => 63,
                'labname' => 'SGS Taiwan Ltd.',
                'labaddr1' => 'No 33, No.35, Wu Chyuan Road',
                'labaddr2' => 'Wuku Industrial Zone',
                'labcity' => 'Taipei',
                'labdistrict' => '',
                'labstate' => 'Taiwan',
                'labcountry' => 'CN',
                'labpostalcode' => '',
            'labphone' => '(+886-2) 2298-3355',
            'labfax' => '(+886-2) 2299-2920',
                'labemail' => '',
                'labwebsite' => 'www.tw.sgs.com',
            ),
            34 =>
            array (
                'wdt_ID' => 35,
                'id' => 64,
            'labname' => 'Specialised Technology Resources (UK) Ltd.',
                'labaddr1' => '10 Portman Rd',
                'labaddr2' => '',
                'labcity' => 'Reading ',
                'labdistrict' => '',
                'labstate' => 'Berkshire',
                'labcountry' => 'UK',
                'labpostalcode' => 'RG30 1EA',
                'labphone' => '0118 939 8700',
                'labfax' => '0118 939 8701',
                'labemail' => '',
                'labwebsite' => '',
            ),
            35 =>
            array (
                'wdt_ID' => 36,
                'id' => 65,
                'labname' => 'STR CT US',
                'labaddr1' => '10 Water Street',
                'labaddr2' => '',
                'labcity' => 'Enfield',
                'labdistrict' => '',
                'labstate' => 'CT',
                'labcountry' => 'USA',
                'labpostalcode' => '06082-4899',
                'labphone' => '8607498371',
                'labfax' => '8607497533',
                'labemail' => 'info@strquality.com',
                'labwebsite' => 'www.strquality.com',
            ),
            36 =>
            array (
                'wdt_ID' => 37,
                'id' => 66,
                'labname' => 'INTERTEK TESTING SERVICES TAIWAN LTD.',
                'labaddr1' => '8F., NO. 423, RUIGUANG RD',
                'labaddr2' => 'NEIHU DISTRICT',
                'labcity' => 'TAIPEI',
                'labdistrict' => 'NEIHU',
                'labstate' => '',
                'labcountry' => 'TAIWAN',
                'labpostalcode' => '11493',
                'labphone' => '',
                'labfax' => '',
                'labemail' => '',
                'labwebsite' => '',
            ),
            37 =>
            array (
                'wdt_ID' => 38,
                'id' => 67,
                'labname' => 'Reliance Technical Service LTD',
                'labaddr1' => '3/F Building D Plalnvlm Industrial Park',
                'labaddr2' => 'Dong Kong Town',
                'labcity' => 'Dong Gong City',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'China',
                'labpostalcode' => '',
                'labphone' => '8676981013838',
                'labfax' => '',
                'labemail' => '',
                'labwebsite' => '',
            ),
            38 =>
            array (
                'wdt_ID' => 39,
                'id' => 68,
                'labname' => 'STC DONGGUAN COMPANY LIMITED',
                'labaddr1' => '68 Fumin Nan Road',
                'labaddr2' => 'Dalang',
                'labcity' => 'Dongguan',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'China',
                'labpostalcode' => '523770',
            'labphone' => '(86 769) 8111 9888',
            'labfax' => '(86 769) 8111 6222',
                'labemail' => 'dgstc@dgstc.org',
                'labwebsite' => 'www.dgstc.org',
            ),
            39 =>
            array (
                'wdt_ID' => 40,
                'id' => 69,
                'labname' => 'GUANGZHOU GRG METROLOGY & TEST CO., LTD.',
                'labaddr1' => '163 PINGYUN ROAD',
                'labaddr2' => 'WEST OF HUANGPU AVENUE',
                'labcity' => 'GUANGZHOU',
                'labdistrict' => 'TIANHE',
                'labstate' => '',
                'labcountry' => 'CHINA',
                'labpostalcode' => '510656',
                'labphone' => '8602038699572',
                'labfax' => '8602038698685',
                'labemail' => '',
                'labwebsite' => 'WWW.GRGTEST.COM',
            ),
            40 =>
            array (
                'wdt_ID' => 41,
                'id' => 70,
                'labname' => 'TUV SUD HONG KONG',
                'labaddr1' => '18/F & 19/F, YUEN LONG TRADING CENTRE',
                'labaddr2' => '33 WANG YIP STREET WEST',
                'labcity' => 'YUEN LONG',
                'labdistrict' => 'NEW TERRITORIES',
                'labstate' => '',
                'labcountry' => 'HONG KONG',
                'labpostalcode' => '',
                'labphone' => '85224433774',
                'labfax' => '85229440005',
                'labemail' => '',
                'labwebsite' => '',
            ),
            41 =>
            array (
                'wdt_ID' => 42,
                'id' => 77,
                'labname' => 'DEKRA TESTING & CERTIFICATION CHINA LTD.',
                'labaddr1' => 'BUILDING A3, NO.3 QIYUN ROAD',
                'labaddr2' => '',
                'labcity' => 'GUANGZHOU',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'CHINA',
                'labpostalcode' => '',
                'labphone' => '862066612000',
                'labfax' => '862066612001',
                'labemail' => 'RAYMOND.YU@DEKRA.COM',
                'labwebsite' => '',
            ),
            42 =>
            array (
                'wdt_ID' => 43,
                'id' => 78,
                'labname' => 'INTERTEK TESTING SERVICES TIANJIN LTD.',
                'labaddr1' => 'No.7 Guyuan Road',
                'labaddr2' => 'Huayuan Hi-Tech Park',
                'labcity' => 'Tianjin',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'China',
                'labpostalcode' => '300384',
                'labphone' => '862283712202',
                'labfax' => '862283712205',
                'labemail' => '',
                'labwebsite' => '',
            ),
            43 =>
            array (
                'wdt_ID' => 44,
                'id' => 79,
                'labname' => 'Intertek Vietnam Ltd.',
                'labaddr1' => '3/F, Au Viet Bldg., No. 1 Le Duc Tho St.',
                'labaddr2' => 'Mai Dich Ward,',
                'labcity' => 'Hanoi',
                'labdistrict' => 'Cau Giay District',
                'labstate' => '',
                'labcountry' => 'Vietnam',
                'labpostalcode' => '',
                'labphone' => '84-4-37337094',
                'labfax' => '84-4-37667093',
                'labemail' => 'consumergoods.vietnam@intertek.com',
                'labwebsite' => 'www.intertek.com',
            ),
            44 =>
            array (
                'wdt_ID' => 45,
                'id' => 80,
                'labname' => 'MSR Laboratories',
                'labaddr1' => 'One New Boston Drive',
                'labaddr2' => 'Suite 1',
                'labcity' => 'Canton',
                'labdistrict' => '',
                'labstate' => 'MA',
                'labcountry' => 'USA',
                'labpostalcode' => '02021-2859',
            'labphone' => '(781)297-2030',
                'labfax' => '',
                'labemail' => '',
                'labwebsite' => '',
            ),
            45 =>
            array (
                'wdt_ID' => 46,
                'id' => 81,
                'labname' => 'Bureau Veritas Vietnam',
                'labaddr1' => 'Lot C7-C9, Conurbation 2, ',
                'labaddr2' => 'Cat Lai Indus. Zone, Dist. 2',
                'labcity' => 'Ho Chi Minh',
                'labdistrict' => 'District 2',
                'labstate' => '',
                'labcountry' => 'Vietnam',
                'labpostalcode' => '',
                'labphone' => '84-8-37421604-6',
                'labfax' => '84-8-37421603',
                'labemail' => '',
                'labwebsite' => 'www.bureauveritas.com/cps',
            ),
            46 =>
            array (
                'wdt_ID' => 47,
                'id' => 82,
                'labname' => 'SGS Guangzhou',
                'labaddr1' => 'No. 198 Kezhu Rd. Scientech Park',
                'labaddr2' => 'Guangzhou Economic & Tech. Dev. District',
                'labcity' => 'Guangzhou',
                'labdistrict' => '',
                'labstate' => '',
                'labcountry' => 'China',
                'labpostalcode' => '510663',
                'labphone' => '86-755-8307-1443',
                'labfax' => '86-20-8207-5027',
                'labemail' => '',
                'labwebsite' => '.com.cn',
            ),
        ));


    }
}